targets:
  $default:
    builders:
      freezed|freezed:
        enabled: true
      json_serializable|json_serializable:
        enabled: true
      hive_generator|hive_generator:
        enabled: true
